<?php

namespace WTWeb\WidgetBundle;

use Symfony\Component\DependencyInjection\Compiler\PassConfig;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use WTWeb\WidgetBundle\Compiler\WidgetCompilerPass;

/**
 * Class WTWebWidgetBundle
 * @package WTWeb\WidgetBundle
 */
class WTWebWidgetBundle extends Bundle
{
    /**
     * @param ContainerBuilder $container
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new WidgetCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 50);

    }
}
